spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

redis:
  host-name: ${REDIS_HOST_NAME:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:#{null}}
  database: ${REDIS_DATABASE:0}

  pubsub:
    channel: ${REDIS_PUBSUB_CHANNEL:post_creation}
  keyword-group: ${REDIS_KEYWORD_GROUP:keyword_group_1}

